# Generated by Django 5.0.7 on 2026-07-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_product_delete_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='instock',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
