# Generated by Django 5.0.7 on 2026-09-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order_is_paid_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
